services:
  - type: web
    name: split-api
    runtime: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: split-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: split-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: split-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: split-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: split-db
          property: password
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: split-web
    env: static
    staticPublishPath: frontend/build/web
    buildCommand: "echo 'Build skipped'"
    plan: free

databases:
  - name: split-db
    plan: free
